INSERT INTO "departments" ("name")
VALUES
    ('Institute on the Environment'),
    ('UMNTC - College of Biological Sciences'),
    ('UMNTC - College of Continuing and Professional Studies'),
    ('UMNTC - College of Dentistry'),
    ('UMNTC - College of Design'),
    ('UMNTC - College of Education and Human Development'),
    ('UMNTC - College of Food, Agricultural and Natural Resource Sciences'),
    ('UMNTC - Law School'),
    ('UMNTC - College of Liberal Arts'),
    ('UMNTC - Carlson School of Management'),
    ('UMNTC - School of Medicine'),
    ('UMNTC - School of Nursing'),
    ('UMNTC - College of Pharmacy'),
    ('UMNTC - Humphrey School of Public Affairs'),
    ('UMNTC - School of Public Health'),
    ('UMNTC - College of Science and Engineering'),
    ('UMNTC - College of Veterinary Medicine'),
    ('UMN Extension / RSDP'),
    ('UMD - College of Arts, Humanities, and Social Sciences'),
    ('UMD - College of Education and Human Service Professions'),
    ('UMD - Labovitz School of Business and Economics'),
    ('UMD - Swenson College of Science and Engineering'),
    ('University of Minnesota Morris'),
    ('University of Minnesota Rochester'),
    ('University of Minnesota Crookston'),
    ('Institute for Advanced Study'),
    ('University of St. Thomas'),
    ('Community organization'),
    ('Individual community member'),
    ('My affiliation is not on this list');


INSERT INTO "user" ("email", "full_name", "google_id", "admin", "avatarPic") VALUES
    ('virginia@example.com', 'Virginia French', 'abc123xyz456', false, 'https://example.com/avatar/virginia_french.jpg'),
    ('brogan@example.com', 'Brogan Pena', 'def456ghi789', false, 'https://example.com/avatar/brogan_pena.jpg'),
    ('sanaa@example.com', 'Sanaa Meadows', 'ghi789abc123', false, 'https://example.com/avatar/sanaa_meadows.jpg'),
    ('darcie@example.com', 'Darcie Glenn', 'jkl012mno345', false, 'https://example.com/avatar/darcie_glenn.jpg'),
    ('kyran@example.com', 'Kyran Terry', 'pqr678stu901', false, 'https://example.com/avatar/kyran_terry.jpg'),
    ('usman@example.com', 'Usman Castillo', 'stu901pqr678', false, 'https://example.com/avatar/usman_castillo.jpg'),
    ('elif@example.com', 'Elif Acevedo', 'mno345jkl012', false, 'https://example.com/avatar/elif_acevedo.jpg'),
    ('aryan@example.com', 'Aryan Hamilton', '123uvw456xyz', false, 'https://example.com/avatar/aryan_hamilton.jpg'),
    ('omari@example.com', 'Omari Holt', '456def789ghi', false, 'https://example.com/avatar/omari_holt.jpg'),
    ('inayah@example.com', 'Inayah Rivers', '789jkl012mno', false, 'https://example.com/avatar/inayah_rivers.jpg'),
    ('harun@example.com', 'Harun Obrien', '234pqr567stu', false, 'https://example.com/avatar/harun_obrien.jpg'),
    ('christina@example.com', 'Christina George', '567vwx890abc', false, 'https://example.com/avatar/christina_george.jpg'),
    ('martha@example.com', 'Martha Brady', '890xyz123uvw', false, 'https://example.com/avatar/martha_brady.jpg'),
    ('amir@example.com', 'Amir Shields', '012abc345def', false, 'https://example.com/avatar/amir_shields.jpg'),
    ('clayton@example.com', 'Clayton Robles', '345stu678pqr', false, 'https://example.com/avatar/clayton_robles.jpg'),
    ('neo@example.com', 'Neo Hanson', '678mno901stu', false, 'https://example.com/avatar/neo_hanson.jpg'),
    ('nicolas@example.com', 'Nicolas Watts', '901xyz234abc', false, 'https://example.com/avatar/nicolas_watts.jpg'),
    ('nikhil@example.com', 'Nikhil Mendez', '234def567ghi', false, 'https://example.com/avatar/nikhil_mendez.jpg'),
    ('teresa@example.com', 'Teresa Delgado', '567jkl890mno', false, 'https://example.com/avatar/teresa_delgado.jpg'),
    ('rishi@example.com', 'Rishi Richards', '890uvw123xyz', false, 'https://example.com/avatar/rishi_richards.jpg');

