--"user"
INSERT INTO "user" ("email", "full_name", "google_id", "admin")
VALUES ()

--"grant_data"
---use the googleSheetsRouter, uncomment certain lines

--"grant_cycle"
---autogenerated

--"scores"
INSERT INTO "scores" ("created_at", "grant_id", "reviewer_id", "assigned_by", "interdisciplinary", "goals", "method_and_design", "budget", "impact", "review_complete")
VALUES ()

--"departments"
INSERT INTO "departments" ("name")
VALUES ("Math"), ("Physics"), ("Public-Health")

--"grant_assignments"
INSERT INTO "grant_assignments" ("assigned_at", "assigned_by", "grant_id", "reviewer_id", "cycle_id")
VALUES ()

--"reviewers"
INSERT INTO "reviewers" ("reviewer_id", "cycle_id", "available_reviews", "dept_id")
VALUES()